export const metadata = {
    title: 'Posts Page',
    description: 'Generated by usama',
}

export default function UsamaLayout({ children }) {
    return (
        <div>
            usama post page layout for common place here
            <h1 className="text-3xl">user name:test@gmail.com</h1>
            {children}
        </div>
    )
}
