export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex bg-red-800">
          <h1 className="text-sm">navbar</h1>
          <h1 className="text-3xl">sidebar</h1>
        </div>
        {children}
        <h1>footer</h1>
      </body>
    </html>
  )
}
